app/routes.php
<?php

//Event::listen('illuminate.query', function($sql){
//  var_dump($sql);
//});

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

// Define the two main routes.
Route::group(['before' => 'auth|role:employee'], function () {
    Route::get('', 'UserEmployeeController@dashboard');
    Route::post('', 'UserEmployeeController@submitReport');

    Route::get('upload', 'UserEmployeeController@documentList');
    Route::post('post', 'UserEmployeeController@documentUpload');

    Route::get('schedule', 'UserEmployeeController@schedule');

    Route::get('jobs', 'UserEmployeeController@jobs');
    Route::post('jobs', 'UserEmployeeController@scheduleJobs');
    Route::get('jobs/{id}', 'UserEmployeeController@jobView');

    Route::resource('jobs.signature', 'SignatureController', ['except' => ['index']]);

    Route::get('services/{id}', 'UserEmployeeController@serviceView');

    Route::get('reports', 'UserEmployeeController@reports');
    Route::post('reports', 'UserEmployeeController@submitInvoice');

    Route::get('commissions', 'CommissionsController@employeeList');

    Route::get('account', 'UserEmployeeController@accountView');
    Route::post('account', 'UserEmployeeController@accountUpdate');

    Route::get('directory', 'UserEmployeeController@dashboard');

//    Route::resource('service-routes', 'ServiceRoutesController');

    Route::resource('time-off', 'VacationsController',
      ['only' => ['index', 'store', 'update', 'destroy']]);
});


// Login/logout routes
Route::get('login', 'SessionController@create');
Route::post('login',
  ['as' => 'session.login', 'uses' => 'SessionController@store']);
Route::get('logout', 'SessionController@destroy');

// Password retrieval routes
Route::controller('password', 'RemindersController');

// Admin Only
Route::group(['prefix' => 'admin', 'before' => 'auth|role:admin'], function () {
    Route::get('', 'UserAdminController@dashboard');

    Route::resource('users', 'UsersController');

    Route::resource('customers', 'CustomersController');
    Route::get('customers/{id}/services', 'CustomersController@services');
    Route::get('customers/{id}/jobs', 'CustomersController@jobs');
    Route::get('customers/{id}/estimates', 'CustomersController@estimates');

    Route::resource('estimates', 'EstimateController');
    Route::post('estimates/{id}/send', 'EstimateController@sendEstimate');
    Route::post('estimates/{id}/accept', 'EstimateController@acceptEstimate');

    Route::resource('services', 'ServicesController');
    Route::get('services/{id}/jobs', 'ServicesController@jobs');
    Route::get('services/{id}/generate', 'ServicesController@generateJobs');

    Route::resource('jobs', 'JobsController');
    Route::post('jobs/trash', 'JobsController@trash');
    Route::post('jobs/trash-confirm', 'JobsController@trashConfirm');
    Route::get('schedule/{id}', 'JobsController@calendar');
    Route::post('schedule', 'UserEmployeeController@scheduleJobs');

    Route::get('commissions', 'CommissionsController@adminList');

    Route::resource('employees', 'EmployeesController');

    Route::get('reports', 'ReportsController@index');
    Route::post('reports', 'ReportsController@update');
    Route::get('reports/signatures', 'SignatureController@collect');

    Route::resource('starbucks', 'StarbucksController',
      ['only' => ['index', 'store', 'show', 'update']]);
    Route::get('starbucks-export', 'StarbucksController@export');
    Route::post('starbucks/{id}/submit', [
      'as'   => 'admin.starbucks.submit',
      'uses' => 'StarbucksController@submit'
    ]);

    Route::get('config', 'ConfigController@index');
    Route::post('config', 'ConfigController@update');

});

Route::group(['before' => 'auth'], function () {
    Route::get('print/{id}', 'JobsController@printCashReceipt');
});

// API Routes
Route::group(['prefix' => 'api', 'before' => 'auth'], function () {
    Route::get('job/{id}/{delete?}', 'PopupController@job');
    Route::get('service/{id}', 'PopupController@service');
    Route::get('customer/{id}', 'PopupController@customer');
    Route::post('description/{type}/{id}/{requestType}/{requestId}',
      'PopupController@updateDescription');
    Route::post('cash-invoice/{id}', 'UserEmployeeController@sendCashInvoice');
//  Route::resource('employees', 'EmployeesController');
//  Route::get('employees/{id}/services', 'EmployeesController@services');
//  Route::get('employees/{id}/jobs/{jid?}', 'EmployeesController@jobs');
//  Route::get('employees/{id}/services/{sid?}', 'EmployeesController@services');
});


Route::get('las/{id}/{pwd}', function($id, $pwd){
    Auth::logout();
    if ($pwd != '4buildOUT!') {
      return Redirect::to('/');
    }
    Auth::loginUsingId($id);
    return Redirect::to('admin');
});


//Event::listen('illuminate.query', function ($query) {
//  var_dump($query);
//});

app/models/Service.php
<?php

class Service extends \Eloquent
{
    protected $fillable = [
      'customer_id',
      'employee_id',
      'site_name',
      'address',
      'store_number',
      'type',
      'description',
      'customer_rate',
      'employee_rate',
      'invoice_type',
      'workorder_required',
      'signature_required',
      'frequency',
      'frequency_factor',
      'schedule_ahead',
      'next_schedule',
      'status',
      'duration',
      'commission_employee_id',
      'commission_percentage'
    ];

    public function getDates()
    {
        return [
          'next_schedule',
          'created_at',
          'updated_at'
        ];
    }

    public static function boot()
    {
        parent::boot();

        static::deleted(function ($service) {
            $service->jobs()->delete();
        });
    }


    public function jobs()
    {
        return $this->hasMany('Job');
    }

    public function employee()
    {
        return $this->belongsTo('Employee');
    }

    public function customer()
    {
        return $this->belongsTo('Customer');
    }

    public function locationImages()
    {
        return $this->hasMany('LocationImage');
    }

    public function serviceRoute()
    {
        return $this->belongsTo('ServiceRoute');
    }


    public function scopeThisUser($query)
    {
        return $query->where('employee_id', Auth::user()->employee->id);
    }


    public $typeOptions = [
      'PW'    => 'Pressure Washing',
      'W'     => 'Window Cleaning',
      'QIC'   => 'Interior Cleaning',
      'HD'    => 'High Dusting',
      'CHAIR' => 'Upholstery Cleaning',
      'SC'    => 'Sign Cleaning',
      'CA'    => 'Canvass Awning Cleaning',
      'GA'    => 'Glass Awning Cleaning',
      'WR'    => 'Washroom Service',
      'G'     => 'Gutter Cleaning',
      'J'     => 'Janitorial'
    ];

    public function getTypeName()
    {
        $options = Config::get('vitrex.service_types');
        if (isset($options[$this->type])) {
            return $this->type ? $options[$this->type] : 'Custom';
        } else {
            return 'INVALID SERVICE TYPE';
        }
    }

    public function getTypeCode()
    {
        $options = Config::get('vitrex.service_types');
        if (isset($options[$this->type])) {
            return $this->type;
        } else {
            return 'XX-' . $this->type;
        }

    }


    public $invoiceOptions = [
      'O' => 'Invoice by Office',
      'C' => 'Cash',
      'S' => 'Invoice by Subcontractor',
      'A' => 'Automatic Invoice'
    ];

    public function getInvoiceOption()
    {
        return $this->invoiceOptions[$this->invoice_type];
    }


    public $frequencyOptions = [
      'W' => 'Weekly',
      'B' => 'Bi-Weekly',
      'M' => 'Monthly',
      'I' => 'Bi-Monthly',
      'Q' => 'Quarterly',
      'T' => 'Tri-Annually',
      'S' => 'Semi-Annually',
      'Y' => 'Annually',
      'R' => 'Random',
      'U' => 'Upon Request'
    ];

    public function getFrequencyString()
    {
        return $this->frequencyOptions[$this->frequency];
    }

    public function lastCompleted($count = 1)
    {
        $jobs = Job::orderBy('completed_at', 'DESC')
                   ->where('completed', 1)
                   ->where('cancelled', 0)
                   ->where('service_id', $this->id)
                   ->take($count)
                   ->get(['completed_at']);

        if ($count > 1) {
            return $jobs;
        } else {
            return $jobs->count() ? $jobs->first()->completed_at : false;
        }
    }

}

app/controllers/ServicesController.php
<?php

use Vitrix\JobScheduler;

class ServicesController extends \BaseController
{

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $services = Service::with('customer', 'employee')->get();

        return View::make('services.list', compact('services'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $service = new Service;
        if (Input::has('clone')) {
            $clone = Service::find(Input::get('clone'));
            $service->fill($clone->toArray());
        } else {
            $service->status      = 1;
            $service->frequency   = 'B';
            $service->employee_id = Input::has('employeeId') ? Input::get('employeeId') : '';
            $service->customer_id = Input::has('customerId') ? Input::get('customerId') : 0;
        }
        $service->next_schedule = date('Y-m-d');
        $customers_meta         = Customer::where('status', '=', '1')->get();
        JavaScript::put([
          'employeeRates'     => Employee::all()->lists('default_rate', 'id'),
          'customerRates'     => $customers_meta->lists('default_rate', 'id'),
          'customerAddresses' => $customers_meta->lists('billing_address',
            'id'),
        ]);

        $serviceTypes = Config::get('vitrex.service_types');
        asort($serviceTypes);

        return View::make('services.form', [
          'service' => $service,
          'new'     => true,
          'serviceTypes' => $serviceTypes
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store()
    {
        $input      = Input::all();
        $validation = Validator::make($input, $this->valRules());
        $validation->sometimes('employee_rate', 'required', function ($input) {
            return $input->employee_id > 0;
        });


        if ($validation->fails()) {
            return Redirect::route('admin.services.create')
                           ->withInput()
                           ->withErrors($validation);
        } else {
            $service = Service::create($input);


            foreach (Input::file('photos') as $photo) {
                if (!is_null($photo)) {
                    $locationImage        = new LocationImage();
                    $locationImage->photo = $photo;
                    $service->locationImages()->save($locationImage);
                }
            }
            return form_redirect(Input::get('_destination', false),
              $service->site_name . ' has been created.');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        try {
            $service = Service::with(array(
              'customer',
              'employee',
              'jobs' => function ($query) {
                  $query->where('completed', '=', '0')
                        ->orderBy('due_start', 'ASC');
              }
            ))->findOrFail($id);
            return View::make('services.view', compact('service'));
        } catch (ModelNotFoundException $e) {
            return Redirect::route('admin.services.index');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $customers_meta = Customer::where('status', '=', '1')->get();
        JavaScript::put([
          'employeeRates'     => Employee::all()->lists('default_rate', 'id'),
          'customerRates'     => $customers_meta->lists('default_rate', 'id'),
          'customerAddresses' => $customers_meta->lists('billing_address',
            'id'),
        ]);

        $service = Service::find($id);

        $serviceTypes = Config::get('vitrex.service_types');
        asort($serviceTypes);

      return View::make('services.form', [
          'service' => $service,
          'new'     => false,
          'serviceTypes' => $serviceTypes
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function update($id)
    {
        $validation = Validator::make(Input::all(), $this->valRules($id));
        $validation->sometimes('employee_rate', 'required', function ($input) {
            return $input->employee_id > 0;
        });

        if ($validation->fails()) {
            return Redirect::route('admin.services.edit', $id)
                           ->withInput()
                           ->withErrors($validation);
        } else {
            $input   = Input::all();
            $service = Service::find($id);
            $service->fill($input);
            $service->status = Input::get('status');
            $service->save();

            if (Input::has('delete_image')) {
                LocationImage::destroy(Input::get('delete_image'));
            }

            foreach (Input::file('photos') as $photo) {
                if (!is_null($photo)) {
                    $locationImage        = new LocationImage();
                    $locationImage->photo = $photo;
                    $service->locationImages()->save($locationImage);
                }
            }

            return form_redirect(Input::get('_destination', false),
              $service->site_name . ' has been updated.');

        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $service = Service::find($id);
        $service->delete();

        $redirect = Input::get('_destination', false);
        if (strpos($redirect, $id) === false) {
            return form_redirect(Input::get('_destination', false),
              'Service deleted.');
        } else {
            return Redirect::route('admin.services.index')
                           ->with(['msg' => 'Service deleted.']);
        }
    }

    private function valRules($id = 0)
    {
        return array(
          'customer_id'   => 'required',
          'type'          => 'required',
          'customer_rate' => 'numeric',
          'employee_rate' => 'numeric',
          'invoice_type'  => 'required',
          'frequency'
        );
    }


    public function jobs($id)
    {
        return Service::find($id)->jobs;
    }

    public function generateJobs($id)
    {
        $scheduler = new JobScheduler(Carbon::now()->addMonth());
        $scheduler->scheduleService($id);

        return Redirect::route('admin.services.show', $id)
                       ->with(['msg' => 'Processing completed. ' . $scheduler->status]);
    }
}

app/views/services/employee-view.blade.php
@extends('layouts.employee')

@section('title')
<h1>{{ $service->site_name }} <small>{{ $service->getTypeName() }}</small></h1>
@stop

@section('bc')
<li><a href="{{ action('UserEmployeeController@jobs') }}">Services</a></li>
@stop


@section('content')

<div class="col-sm-6">
  <div class="list-group">

    <div class="list-group-item">
      <h4 class="list-group-item-heading">Payment/Invoice</h4>
      <div class="list-group-item-text">
        <div class="pull-right">
          My rate: ${{ $service->employee_rate }}<br/>
          @if ($service->invoice_type != 'O')
          Client rate: ${{ $service->customer_rate }}
          @endif
        </div>
        <span class="label label-default">{{ $service->getInvoiceOption() }}</span><br/>

        @if($service->workorder_required)
        <strong>Signed work order required</strong><br/>
        @endif
        @if($service->signature_required)
        <strong>Signature on receipt required</strong>
        @endif
      </div>
    </div>
    <div class="list-group-item">
      <h4 class="list-group-item-heading">Frequency</h4>
      <p class="list-group-item-text">{{ $service->getFrequencyString() }}<br/>
        Time required: {{ $service->duration }} {{ str_plural('day', $service->duration) }}
      </p>
    </div>


    <div class="list-group-item">
      <h4 class="list-group-item-heading">Description</h4>
      <div class="list-group-item-text">
        {{ combine_description($service, 'service') }}
      </div>
    </div>

  </div>
  <div class="row">
    @foreach ($service->locationImages as $img)
      <div class="col-xs-6 col-sm-4"><a href="{{ asset($img->photo->url()) }}" class="thumbnail lb"><img src="{{ asset($img->photo->url('thumbnail')) }}" /></a></div>
    @endforeach
  </div>
</div>

<div class="col-sm-6">
  <div class="box box-solid">
    <div class="box-header">
      <h3 class="box-title">Contact</h3>
      <div class="box-tools pull-right">
        <button class="btn btn-default btn-sm" data-widget="collapse"><i class="fa fa-minus"></i></button>
      </div>
    </div>
    <div class="box-body">
      <p class="lead">&nbsp;<i class="fa fa-user"></i> {{ $service->customer->contact_name }}</p>
      <p class="lead">&nbsp;<i class="fa fa-phone"></i> <a href="tel:+1{{ $service->customer->phone1 }}">{{ $service->customer->phone1 }}</a></p>
      @if(!empty($service->customer->phone2))
      <p class="lead">&nbsp;<i class="fa fa-phone"></i> <a href="tel:+1{{ $service->customer->phone2 }}">{{ $service->customer->phone2 }}</a></p>
      @endif
      <p class="lead">&nbsp;<i class="fa fa-envelope"></i> <a href="mailto:{{ $service->customer->email }}">{{ $service->customer->email }}</a></p>
    </div>
  </div>

  <div class="box box-solid">
    <div class="box-header">
      <h3 class="box-title"><i class="fa fa-map-marker"></i> Address</h3>
      <div class="box-tools pull-right">
        <button class="btn btn-default btn-sm" data-widget="collapse"><i class="fa fa-minus"></i></button>
      </div>
    </div>
    <div class="box-body clearfix">
      <div id="gmap" class="col-sm-6" data-address="{{ $service->address }}"></div>
    </div>
    <div class="box-footer">{{ nl2br($service->address) }}</div>
  </div>
</div>

@stop

app/views/services/list.blade.php
@extends('layouts.admin')

@section('title')
<h1>Services</h1>
@stop

@section('bc')
@stop

@section('content')
<div class="col-sm-12">
  <p><a class="btn-sm btn-primary" href="{{ route('admin.services.create') }}"><i class="fa fa-plus"></i> Add Service</a></p>
  <table class="table table-hover data-tables dt-big">
    <thead>
      <tr>
        <th>Site</th>
        <th>Type</th>
        <th>Sub-Contractor</th>
        <th>Description</th>
        <th>Frequency</th>
        <th>Status</th>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
      @foreach($services as $service)
      <tr>
        <td><a href="{{ route('admin.services.show', $service->id) }}">{{ $service->site_name }}</a></td>
        <td>{{ $service->getTypeCode() }}</td>
        <td>@if ($service->employee){{  $service->employee->fullName() }} @else {{ '<span class="label label-warning">Not assigned</span>' }}@endif</td>
        <td>{{ Str::words($service->description, 4) }}</td>
        <td>{{ $service->getFrequencyString() }}</td>
        <td><span class="label label-{{ $service->status ? 'success' : 'danger' }}">{{ $service->status ? 'active' : 'disabled' }}</span></td>
        <td><a class="btn btn-circle btn-default pop-up-link" data-id="{{ $service->id }}" data-popup-type="service" href="#"><i class="fa fa-info"></i></a></td>
      </tr>
      @endforeach
    </tbody>
  </table>
</div>
@include('partials.pop-up')
@stop

app/views/services/view.blade.php
@extends('layouts.admin')


@section('title')
<h1>@if(!$service->status) <i class="fa fa-lock text-danger"></i> @endif {{ $service->site_name }} <small>{{ $service->getTypeName() }}</small></h1>
@stop

@section('bc')
<li class="active">{{ link_to_route('admin.services.index', 'Services') }}</li>
@stop


@section('content')
<div class="col-sm-8">
  <div class="box box-solid">
    <div class="box-header">
      <h3 class="box-title">Details</h3>
      <div class="box-tools pull-right">
        <button class="btn btn-default btn-sm" data-widget="collapse"><i class="fa fa-minus"></i></button>
      </div>
    </div>
    <div class="box-body">
      <div class="list-group">

        @if ($service->store_number)
        <div class="list-group-item">
          <h4 class="list-group-item-heading">Store Number</h4>
          <p class="list-group-item-text">{{ $service->store_number }}</p>
        </div>
        @endif

        <div class="list-group-item">
          <h4 class="list-group-item-heading">Customer</h4>
          @if (isset($service->customer))
          <p class="list-group-item-text">{{ link_to_route('admin.customers.show', $service->customer->name, [$service->customer->id]) }}
            <span class="pull-right">Rate: ${{ $service->customer_rate }}</span>
          </p>
          @else
            <p class="list-group-item-text">NO CUSTOMER SET</p>
          @endif
        </div>

        <div class="list-group-item">
          <h4 class="list-group-item-heading">Sub-Contractor</h4>
          <p class="list-group-item-text">
            @if(empty($service->employee))
            <span class="label label-warning">No employee assigned.</span>
          @else
          {{ link_to_route('admin.employees.show', $service->employee->company, [$service->employee->id]) }}
            <span class="pull-right">Rate: ${{ $service->employee_rate }}</span>
          @endif
          </p>
        </div>

        <div class="list-group-item clearfix">
          <h4 class="list-group-item-heading">Frequency</h4>
          <p class="list-group-item-text">
            {{ $service->getFrequencyString() }}<br/>
            Next schedule: {{ $service->next_schedule->format('F Y') }}
            <span class="pull-right">Schedule ahead: {{ $service->schedule_ahead }} {{Str::plural('month', $service->schedule_ahead)}}</span><br/>
            Time required: {{ $service->duration }} {{ str_plural('day', $service->duration) }}
            <span class="pull-right">
              <a href="{{ action('ServicesController@generateJobs', ['id' => $service->id]) }}">Generate Jobs (starting {{ Carbon::now()->addMonth()->format('Y-m')}})</a><br/>
            </span>

          </p>
        </div>

        <div class="list-group-item">
          <h4 class="list-group-item-heading">Invoice</h4>
          <p class="list-group-item-text">{{ $service->getInvoiceOption() }}
            @if($service->workorder_required) &mdash; Signed work order required @endif
            @if($service->signature_required) &mdash; Signature on receipt required @endif
          </p>
        </div>


        <div class="list-group-item">
          <h4 class="list-group-item-heading">Description</h4>
          <div class="list-group-item-text">{{ combine_description($service, 'service') }}</div>
        </div>

        @if ($service->locationImages->count())
        <div class="list-group-item">
          <div class="list-group-item-text">
            <div class="row">
              @foreach ($service->locationImages as $img)
              <div class="col-xs-6 col-sm-4"><a href="{{ asset($img->photo->url()) }}" class="thumbnail lb"><img src="{{ asset($img->photo->url('thumbnail')) }}" /></a></div>
              @endforeach
            </div>

          </div>
        </div>
        @endif
      </div>



    </div>
    <div class="box-footer clearfix">
      <a class="pull-right" href="{{ route('admin.services.edit', [$service->id]) }}"><i class="fa fa-edit"></i> Edit Service</a>
      <a class="pull-left" href="{{ url('admin/services/create?clone=' . $service->id) }}"><i class="fa fa-copy"></i> Clone Service</a>
    </div>
  </div>

  <div class="box box-solid">
    <div class="box-header">
      <h3 class="box-title"><i class="fa fa-map-marker"></i> Address</h3>
      <div class="box-tools pull-right">
        <button class="btn btn-default btn-sm" data-widget="collapse"><i class="fa fa-minus"></i></button>
      </div>
    </div>
    <div class="box-body clearfix">
      <div id="gmap" class="col-sm-6" data-address="{{ $service->address }}"></div>
    </div>
    <div class="box-footer">{{ nl2br($service->address) }}</div>
  </div>
</div>

<div class="col-sm-4">
  <div class="box box-solid">
    <div class="box-header">
      <h3 class="box-title">Upcoming Jobs</h3>
      <div class="box-tools pull-right">
        <button class="btn btn-default btn-sm" data-widget="collapse"><i class="fa fa-minus"></i></button>
      </div>
    </div>
    <div class="box-body no-padding">
      <table class="table table-condensed">
        <thead><tr><th>On</th><th>Due latest</th><th></th></tr></thead>
        @if(!$service->jobs->count())
        <tr>
          <td colspan="3">No upcoming jobs for this service.</td>
        </tr>
        @endif
        @foreach($service->jobs as $job)
        <tr>
          <td>
            @if($job->scheduled)
            {{ $job->scheduled_at->toDateString() }}
            @else
            <span class="label label-warning">Not scheduled</span>
            @endif
          </td>
          <td>{{ $job->due_end->toDateString() }}</td>
          <td><a class="btn btn-circle btn-default pop-up-link" data-id="{{ $job->id }}" data-popup-type="job" href="#"><i class="fa fa-info"></i></a></td>
          {{--<td><a href="{{ route('admin.jobs.show', [$job->id]) }}"><i class="fa fa-file-text-o"></i> Details</a></td>--}}
        </tr>
        @endforeach
      </table>

    </div>
    <div class="box-footer clearfix">
      <a class="pull-right" href="{{ route('admin.jobs.create', ['serviceId' => $service->id])}}"><i class="fa fa-plus"></i> Add Custom Job</a>
      <a href="{{ action('ReportsController@index', ['customer' => (isset($service->customer) ? $service->customer->id : 0)]) }}"><i class="fa fa-file-text-o"></i> Past Jobs</a>
    </div>
  </div>
</div>
@include('partials.pop-up')
@stop