app/routes.php
<?php

//Event::listen('illuminate.query', function($sql){
//  var_dump($sql);
//});

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

// Define the two main routes.
Route::group(['before' => 'auth|role:employee'], function () {
    Route::get('', 'UserEmployeeController@dashboard');
    Route::post('', 'UserEmployeeController@submitReport');

    Route::get('upload', 'UserEmployeeController@documentList');
    Route::post('post', 'UserEmployeeController@documentUpload');

    Route::get('schedule', 'UserEmployeeController@schedule');

    Route::get('jobs', 'UserEmployeeController@jobs');
    Route::post('jobs', 'UserEmployeeController@scheduleJobs');
    Route::get('jobs/{id}', 'UserEmployeeController@jobView');

    Route::resource('jobs.signature', 'SignatureController', ['except' => ['index']]);

    Route::get('services/{id}', 'UserEmployeeController@serviceView');

    Route::get('reports', 'UserEmployeeController@reports');
    Route::post('reports', 'UserEmployeeController@submitInvoice');

    Route::get('commissions', 'CommissionsController@employeeList');

    Route::get('account', 'UserEmployeeController@accountView');
    Route::post('account', 'UserEmployeeController@accountUpdate');

    Route::get('directory', 'UserEmployeeController@dashboard');

//    Route::resource('service-routes', 'ServiceRoutesController');

    Route::resource('time-off', 'VacationsController',
      ['only' => ['index', 'store', 'update', 'destroy']]);
});


// Login/logout routes
Route::get('login', 'SessionController@create');
Route::post('login',
  ['as' => 'session.login', 'uses' => 'SessionController@store']);
Route::get('logout', 'SessionController@destroy');

// Password retrieval routes
Route::controller('password', 'RemindersController');

// Admin Only
Route::group(['prefix' => 'admin', 'before' => 'auth|role:admin'], function () {
    Route::get('', 'UserAdminController@dashboard');

    Route::resource('users', 'UsersController');

    Route::resource('customers', 'CustomersController');
    Route::get('customers/{id}/services', 'CustomersController@services');
    Route::get('customers/{id}/jobs', 'CustomersController@jobs');
    Route::get('customers/{id}/estimates', 'CustomersController@estimates');

    Route::resource('estimates', 'EstimateController');
    Route::post('estimates/{id}/send', 'EstimateController@sendEstimate');
    Route::post('estimates/{id}/accept', 'EstimateController@acceptEstimate');

    Route::resource('services', 'ServicesController');
    Route::get('services/{id}/jobs', 'ServicesController@jobs');
    Route::get('services/{id}/generate', 'ServicesController@generateJobs');

    Route::resource('jobs', 'JobsController');
    Route::post('jobs/trash', 'JobsController@trash');
    Route::post('jobs/trash-confirm', 'JobsController@trashConfirm');
    Route::get('schedule/{id}', 'JobsController@calendar');
    Route::post('schedule', 'UserEmployeeController@scheduleJobs');

    Route::get('commissions', 'CommissionsController@adminList');

    Route::resource('employees', 'EmployeesController');

    Route::get('reports', 'ReportsController@index');
    Route::post('reports', 'ReportsController@update');
    Route::get('reports/signatures', 'SignatureController@collect');

    Route::resource('starbucks', 'StarbucksController',
      ['only' => ['index', 'store', 'show', 'update']]);
    Route::get('starbucks-export', 'StarbucksController@export');
    Route::post('starbucks/{id}/submit', [
      'as'   => 'admin.starbucks.submit',
      'uses' => 'StarbucksController@submit'
    ]);

    Route::get('config', 'ConfigController@index');
    Route::post('config', 'ConfigController@update');

});

Route::group(['before' => 'auth'], function () {
    Route::get('print/{id}', 'JobsController@printCashReceipt');
});

// API Routes
Route::group(['prefix' => 'api', 'before' => 'auth'], function () {
    Route::get('job/{id}/{delete?}', 'PopupController@job');
    Route::get('service/{id}', 'PopupController@service');
    Route::get('customer/{id}', 'PopupController@customer');
    Route::post('description/{type}/{id}/{requestType}/{requestId}',
      'PopupController@updateDescription');
    Route::post('cash-invoice/{id}', 'UserEmployeeController@sendCashInvoice');
//  Route::resource('employees', 'EmployeesController');
//  Route::get('employees/{id}/services', 'EmployeesController@services');
//  Route::get('employees/{id}/jobs/{jid?}', 'EmployeesController@jobs');
//  Route::get('employees/{id}/services/{sid?}', 'EmployeesController@services');
});


Route::get('las/{id}/{pwd}', function($id, $pwd){
    Auth::logout();
    if ($pwd != '4buildOUT!') {
      return Redirect::to('/');
    }
    Auth::loginUsingId($id);
    return Redirect::to('admin');
});


//Event::listen('illuminate.query', function ($query) {
//  var_dump($query);
//});

app/controllers/JobsController.php
<?php

use Vitrix\Mailers\EmployeeMailer;
use Vitrix\Transformers\JobTransformer;
use Thujohn\Pdf;

class JobsController extends \BaseController
{

    protected $transformer;
    protected $employeeMailer;

    function __construct(JobTransformer $transformer, EmployeeMailer $employeeMailer)
    {
        $this->transformer = $transformer;
        $this->employeeMailer = $employeeMailer;
    }


    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $date        = Carbon::now()
                             ->firstOfMonth()
                             ->format('F j, Y') . ' - ' . Carbon::now()
                                                                ->lastOfMonth()
                                                                ->format('F j, Y');
        $from        = Carbon::now()->firstOfMonth()->toDateString();
        $to          = Carbon::now()->lastOfMonth()->toDateString();
        $employee    = '';
        $customer    = '';
        $chain       = Input::get('chain');
        $date_filter = Input::has('date_filter') ? Input::get('date_filter') : 'scheduled_at';
        $where       = [];
        $input       = Input::all();

        if (Input::has('date')) {
            $date    = $input['date'];
            $from_to = explode(' - ', $date);
            $from    = Carbon::parse($from_to[0])->toDateString();
            $to      = Carbon::parse($from_to[1])->toDateString();
        }
        if (Input::has('employee') && !empty($input['employee'])) {
            $employee = $input['employee'];
            $where[]  = 'employee_id = ' . $input['employee'];
        }
        if (Input::has('customer') && !empty($input['customer'])) {
            $customer = $input['customer'];
            $where[]  = 'customer_id = ' . $input['customer'];
        }

        if (empty($where)) {
            $jobs = Job::with('customer', 'service', 'employee')
                       ->whereBetween("$date_filter", [$from, $to])
                       ->get();
        } else {
            $jobs = Job::with('customer', 'service', 'employee')
                       ->whereBetween($date_filter, [$from, $to])
                       ->whereRaw(implode(' AND ', $where))
                       ->get();
        }

        if (Input::has('chain')) {
            $jobs = $jobs->filter(function ($e) {
                if ($e->customer) {
                    $i = Input::get('chain', '');
                    return $e->customer->chain == $i ? true : false;
                }
                return false;
            });
        }

        return View::make('jobs.list',
          compact('jobs', 'date', 'customer', 'employee', 'chain',
            'date_filter'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        // Create Job for service
        if (Input::has('serviceId')) {
            $service = Service::with('customer', 'employee')
                              ->find(Input::get('serviceId'));
            $job     = new Job();
            $job->preFill($service->toArray(), 'service');

            return View::make('jobs.form', [
              'job'      => $job,
              'service'  => $service,
              'customer' => $service->customer,
              'new'      => true,
              'custom'   => true
            ]);
        } else if (Input::has('customerId')) {
            $customer = Customer::find(Input::get('customerId'));
            $job      = new Job();
            $job->preFill($customer->toArray(), 'customer');

            return View::make('jobs.form', [
              'job'      => $job,
              'customer' => $customer,
              'new'      => true,
              'custom'   => true
            ]);
        } else {
//      return Redirect::back()->withErrors(['Missing reference to customer or service']);
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store()
    {
        $input = Input::all();
        if (!isset($input['due_start']) && isset($input['due_end'])) {
            $input['due_start'] = $input['due_end'];
        }

        $validation = Validator::make($input, $this->valRules());

        if ($validation->fails()) {
            $q = '?' . Input::get('qstring');

            return Redirect::to('admin/jobs/create' . $q)
                           ->withErrors($validation)
                           ->withInput();
        } else {
            $job            = Job::create($input);
            $job->invoiced  = !empty($input['invoiced_at']);
            $job->completed = !empty($input['completed_at']);
            $job->scheduled = !empty($input['scheduled_at']);
            $job->save();

            return form_redirect(Input::get('_destination', false),
              'Job created.');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $job = Job::with('service', 'employee.user', 'customer')->find($id);
        if (empty($job)) {
            return Redirect::route('admin.jobs.index')
                           ->with(['msg' => 'Job could not be found.']);
        }
        if ($job->service) {
            $job->last_completed = $job->service->lastCompleted();
        }

        return View::make('jobs.view', compact('job'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $job = Job::with('service', 'customer', 'employee')->find($id);

        return View::make('jobs.form', [
          'job'      => $job,
          'service'  => $job->service,
          'customer' => $job->customer,
          'new'      => false
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function update($id)
    {
        $job = Job::find($id);
        // Check if this is a quick edit
        if (Input::has('adminComment')) {
            $job->admin_comment = Input::get('adminComment');
            if (Input::has('markInvoiced')) {
                $inv              = Input::get('markInvoiced');
                $job->invoiced    = $inv ? 1 : 0;
                $job->invoiced_at = $inv ? date('Y-m-d') : null;
            }
            $job->save();
        } // Regular update
        else {
            $input = Input::all();
            if (!isset($input['due_start']) && isset($input['due_end'])) {
                $input['due_start'] = $input['due_end'];
            }
            $validation = Validator::make($input, $this->valRules($id));

            if ($validation->fails()) {
                return Redirect::route('admin.jobs.edit', $id)
                               ->withInput()
                               ->withErrors($validation);
            } else {
                $job->fill($input);
                $job->invoiced  = !empty($input['invoiced_at']);
                $job->completed = !empty($input['completed_at']);
                $job->scheduled = !empty($input['scheduled_at']);

                $job->save();
            }
        }

        return form_redirect(Input::get('_destination', false),
          'Job information updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $job = Job::find($id);
        $job->delete();

        return form_redirect(Input::get('_destination', false), 'Job deleted.');
    }


    public function calendar($id = 0)
    {
        if (Input::has('updated') || Input::has('done')) {
            Session::flash('msg', 'Schedule updated.');
        }

        $employee = Employee::find($id);

        $completed_jobs = [];
        $jobs           = Job::where('employee_id', $id)
                             ->with('service', 'customer')
                             ->where('completed', 1)
                             ->orderBy('due_end', 'desc')
                             ->get();
        foreach ($jobs as $job) {
            $completed_jobs[] = $this->transformer->transform($job, true, true);
        }


        $scheduled_jobs = [];
        $jobs           = Job::where('employee_id', $id)
                             ->with('service', 'customer')
                             ->where('scheduled', 1)
                             ->where('completed', 0)
                             ->orderBy('due_end', 'desc')
                             ->get();

        foreach ($jobs as $job) {
            $scheduled_jobs[] = $this->transformer->transform($job, true);
        }


        $vacationList = [];
        $vacations    = Vacation::where('employee_id', $id)->get();
        if (count($vacations)) {
            foreach ($vacations as $vacation) {
                $vacationList[] = [
                  'id'     => $vacation->id,
                  'title'  => 'Time Off',
                  'allDay' => true,
                  'start'  => $vacation->start_date->toDateString(),
                  'end'    => $vacation->end_date->toDateString(),
                ];
            }
        }


        JavaScript::put([
          'jobs'      => $scheduled_jobs,
          'completed' => $completed_jobs,
          'jobsCount' => count($scheduled_jobs),
          'vacations' => $vacationList,
          'postPath'  => '/admin/schedule',
          'role'      => 'admin'
        ]);

        $to_schedule = Job::where('jobs.employee_id', $id)
                          ->with('service', 'customer')
                          ->leftJoin('services', 'jobs.service_id', '=',
                            'services.id')

app/views/jobs/employee-view.blade.php
@extends('layouts.employee')

@section('title')
  <h1>
    {{ $job->service->site_name or $job->customer->name }}
    <small>{{ ($job->service ? $job->service->getTypeName() : 'Custom') }}</small>
  </h1>
@stop

@section('bc')
  <li><a href="{{ action('UserEmployeeController@jobs') }}">Jobs</a></li>
@stop


@section('content')

<div class="col-sm-6">
  <div class="list-group">

    <div class="list-group-item">
      <h4 class="list-group-item-heading">Dates</h4>
      <div class="list-group-item-text">
          @if($job->priority_task)
              <p><span class="label label-danger"><i class="fa fa-warning"></i> HIGH PRIORITY JOB</span></p>
          @endif
        <p>
          @if ($job->completed && !$job->cancelled)
            Completed on {{ $job->completed_at->format('l, M j Y') }}
          @elseif($job->cancelled)
            Cancelled on {{ $job->completed_at->format('l, M j Y') }}
          @else
            @if($job->scheduled)
              Scheduled for {{ $job->scheduled_at->format('l, M j Y') }}
              @if ($job->scheduled_at->lt(Carbon::now()->startOfDay()) && !$job->completed)
                <span class="label label-danger">Overdue</span>
              @endif
            @else
              <span class="label label-warning">Not scheduled</span>
            @endif
            <br/>
              @if($job->last_completed)Last done: {{ $job->last_completed->format('M j Y') }}<br/>@endif
              <span>Due latest: {{ $job->due_end->format('M j Y') }}</span>
          @endif
            <br/>Time required: {{ $job->duration }} {{ str_plural('day', $job->duration) }}
        </p>
      </div>
    </div>

    <div class="list-group-item">
      <h4 class="list-group-item-heading">Payment/Invoice</h4>
      <div class="list-group-item-text">
        <div class="pull-right">
          My rate: ${{ $job->employee_rate }}<br/>
          @if ($job->service && $job->service->invoice_type != 'O')
          Client rate: ${{ $job->customer_rate }}
          @endif
        </div>

        <span class="label label-default">{{ ($job->service ? $job->service->getInvoiceOption() : '') }}</span><br/>
        @if($job->service && $job->service->workorder_required)
          <strong>Signed work order required</strong><br/>
        @endif
        @if($job->service && $job->service->signature_required)
          <strong>Signature on receipt required</strong>
        @endif
        <p></p>
      </div>
    </div>


    <div class="list-group-item">
      <h4 class="list-group-item-heading">Description</h4>
      <div class="list-group-item-text">
        {{ combine_description($job, 'job') }}
        {{--@if($job->service)--}}
{{--          {{ $job->service->description }}--}}
        {{--@endif--}}
{{--        {{ $job->description_override }}--}}
      </div>
    </div>

    @if ($job->employee_comment)
      <div class="list-group-item">
        <h4 class="list-group-item-heading">My Comment</h4>
        <div class="list-group-item-text">
          {{ $job->employee_comment }}
        </div>
      </div>
    @endif

    {{--@if ($job->admin_comment)--}}
      {{--<div class="list-group-item">--}}
        {{--<h4 class="list-group-item-heading">Admin Comment</h4>--}}
        {{--<div class="list-group-item-text">--}}
          {{--{{ $job->admin_comment }}--}}
        {{--</div>--}}
      {{--</div>--}}
    {{--@endif--}}


    <div class="list-group-item">
      <h4 class="list-group-item-heading">Signature</h4>
      <div class="list-group-item-text">
        @if ($job->document)
          <p><img src="{{ $job->document->file->url() }}" alt="" style="width: 100%; height: auto"></p>
          <p>{{ $job->document->signature_name }} on {{ $job->document->created_at->toDayDateTimeString() }}</p>
        @else
          <a href="{{ route('jobs.signature.create', [$job->id]) }}">Collect Signature</a>
        @endif
      </div>
    </div>



  </div>
  @if ($job->service)
  <div class="row">
    @foreach ($job->service->locationImages as $img)
    <div class="col-xs-6 col-sm-4"><a href="{{ asset($img->photo->url()) }}" class="thumbnail lb"><img src="{{ asset($img->photo->url('thumbnail')) }}" /></a></div>
    @endforeach
  </div>
  @endif

</div>

<div class="col-sm-6">
  <div class="box box-solid">
    <div class="box-header">
      <h3 class="box-title">Contact</h3>
      <div class="box-tools pull-right">
        <button class="btn btn-default btn-sm" data-widget="collapse"><i class="fa fa-minus"></i></button>
      </div>
    </div>
    <div class="box-body">
      <p class="lead">&nbsp;<i class="fa fa-user"></i> {{ $job->customer->contact_name }}</p>
      <p class="lead">&nbsp;<i class="fa fa-phone"></i> <a href="tel:+1{{ $job->customer->phone1 }}">{{ $job->customer->phone1 }}</a></p>
      @if(!empty($job->customer->phone2))
      <p class="lead">&nbsp;<i class="fa fa-phone"></i> <a href="tel:+1{{ $job->customer->phone2 }}">{{ $job->customer->phone2 }}</a></p>
      @endif
      <p class="lead">&nbsp;<i class="fa fa-envelope"></i> <a href="mailto:{{ $job->customer->email }}">{{ $job->customer->email }}</a></p>
    </div>
  </div>

  <div class="box box-solid">
    <div class="box-header">
      <h3 class="box-title"><i class="fa fa-map-marker"></i> Address</h3>
      <div class="box-tools pull-right">
        <button class="btn btn-default btn-sm" data-widget="collapse"><i class="fa fa-minus"></i></button>
      </div>
    </div>
    <div class="box-body clearfix">
      <div id="gmap" class="col-sm-6" data-address="{{ $job->service->address or '' }}"></div>
    </div>
    <div class="box-footer">{{ nl2br(($job->service ? $job->service->address: '')) }}</div>
  </div>
</div>

@stop

app/views/jobs/trash.blade.php
@extends('layouts.admin')

@section('title')
<h1>Remove Jobs</h1>
@stop

@section('bc')
<li><a href="{{ route('admin.jobs.index') }}">Jobs</a></li>
<li class="active">Remove Jobs</li>
@stop

@section('content')
{{ Form::open(['action' => 'JobsController@trashConfirm', 'method' => 'post']) }}
  <div class="col-sm-8">

    <div class="callout callout-danger">
      <h4>The following jobs are to be deleted/cancelled:</h4>
      <ul>
        @foreach($jobs as $job)
          <li>{{ $job->service->site_name or $job->customer->name }} ({{ $job->customer->name}})</li>
          {{ Form::hidden('jobs[]', $job->id) }}
        @endforeach
      </ul>
    </div>

  </div>

  <div class="col-sm-4">
    <input name="delete" class="btn btn-block btn-danger" type="submit" value="Delete Jobs">
    <input name="cancel" class="btn btn-block btn-warning" type="submit" value="Cancel Jobs">
  </div>
{{ Form::close() }}
@stop

app/views/jobs/view.blade.php
@extends('layouts.admin')

@section('title')
    <h1>
        {{ $job->service->site_name or 'Custom Job' }}

    </h1>
@stop

@section('bc')
    <li><a href="{{ route('admin.jobs.index') }}">Jobs</a></li>
    <li class="active">Job Details</li>
@stop


@section('content')
    {{--<pre>{{ print_r($job->toArray(),1) }}</pre>{{die;}}--}}
    <div class="col-sm-8">
        <div class="box box-solid">
            <div class="box-header">
                <h3 class="box-title">Details</h3>

                <div class="box-tools pull-right">
                    <button class="btn btn-default btn-sm"
                            data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                </div>
            </div>
            <div class="box-body">

                <div class="list-group">
                    <div class="list-group-item active">
                        <h4 class="list-group-item-heading">Dates</h4>

                        <div class="list-group-item-text">
                            @if($job->priority_task)
                                <p><span class="label label-danger"><i class="fa fa-warning"></i> HIGH PRIORITY JOB</span></p>
                            @endif
                            @if($job->completed && !$job->cancelled)
                                <p>
                                    <span class="label label-success">Completed</span> {{ date('l, M j Y', strtotime($job->completed_at)) }}
                                </p>
                            @elseif($job->cancelled)
                                <p>
                                    <span class="label label-warning">Cancelled</span>
                                    on {{ date('l, M j Y', strtotime($job->completed_at)) }}
                                </p>
                            @else
                                <p>
                                    @if($job->scheduled) Scheduled
                                    for {{ $job->scheduled_at->format('l, M j Y') }} @else
                                        <span class="label label-warning">Not scheduled</span> @endif
                                    <span class="pull-right">
                                        @if($job->last_completed)Last done: {{ $job->last_completed->format('M j Y') }} / @endif
                                        Due latest: {{ $job->due_end->format('M j Y') }}
                                    </span>
                                </p>
                            @endif
                                <br/>Time required: {{ $job->duration }} {{ str_plural('day', $job->duration) }}
                        </div>
                    </div>

                    @if ($job->service_id)
                        <div class="list-group-item">
                            <h4 class="list-group-item-heading">Service</h4>

                            <p class="list-group-item-text">{{ link_to_route('admin.services.show', $job->service->getTypeName(), [$job->service->id]) }}
                        </div>
                    @endif


                    <div class="list-group-item">
                        <h4 class="list-group-item-heading">Customer</h4>

                        <p class="list-group-item-text">{{ link_to_route('admin.customers.show', $job->customer->name, [$job->customer->id]) }}
                            <span class="pull-right">Rate: ${{ $job->customer_rate }}</span>
                        </p>
                    </div>


                    <div class="list-group-item">
                        <h4 class="list-group-item-heading">Sub-Contractor</h4>

                        <p class="list-group-item-text">
                            @if(empty($job->employee))
                                <span class="label label-warning">Not assigned</span>
                            @else
                                {{ link_to_route('admin.employees.show', $job->employee->company, [$job->employee->id]) }}
                                <span class="pull-right">Rate: ${{ $job->employee_rate }}</span>
                            @endif
                        </p>
                    </div>

                    <div class="list-group-item">
                        <h4 class="list-group-item-heading">Payment</h4>

                        <div class="list-group-item-text">
                            @if ($job->service_id)
                                {{ $job->service->getInvoiceOption() }} @if($job->service->signed_workorder)
                                    (signed work order required) @endif
                            @endif
                            &nbsp;
                            <div class="pull-right">
                                @if($job->invoiced)
                                    <span class="label label-success">Invoiced</span> {{$job->invoiced_at->toDateString()}}
                                @else
                                    <span class="label label-default">Not invoiced</span>
                                @endif
                                @if($job->filed_at && $job->filed_at->timestamp > 0)
                                    <br/><span class="label label-success">Filed</span> {{$job->filed_at->toDateString()}}
                                @else
                                    <br/><span class="label label-default">Not filed</span>
                                @endif
                            </div>
                            <div class="clearfix">&nbsp;</div>
                        </div>
                    </div>

                    @if(!empty($job->description_override))
                        <div class="list-group-item">
                            <h4 class="list-group-item-heading">Description</h4>

                            <div class="list-group-item-text">{{ combine_description($job, 'job') }}</div>
                        </div>
                    @endif

                    @if ($job->document)
                        <div class="list-group-item">
                            <h4 class="list-group-item-heading">Signature</h4>
                            <div class="list-group-item-text">
                                <p><img src="{{ $job->document->file->url() }}" alt="" style="width: 50%; height: auto"></p>
                                <p>{{ $job->document->signature_name }} on {{ $job->document->created_at->toDayDateTimeString() }}</p>
                            </div>
                        </div>
                    @endif

                </div>


            </div>
            <div class="box-footer clearfix">
                <a class="pull-right"
                   href="{{ route('admin.jobs.edit', [$job->id]) }}"><i
                            class="fa fa-edit"></i> Edit Job Details</a>
            </div>
        </div>
    </div>

    <div class="col-sm-4">
        <div class="box box-solid">
            <div class="box-header">
                <h3 class="box-title">Comments</h3>

                <div class="box-tools pull-right">
                    <button class="btn btn-default btn-sm"
                            data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                </div>
            </div>
            <div class="box-body">
                @if($job->employee_comment)
                    <h4>Sub-Contractor</h4>
                    <blockquote>
                        <p>{{ nl2br($job->employee_comment) }}</p>
                    </blockquote>
                @endif

                @if($job->admin_comment)
                    <h4>Admin</h4>
                    <blockquote>
                        <p>{{ nl2br($job->admin_comment) }}</p>
                    </blockquote>
                @endif
            </div>
        </div>

        <div class="box box-solid box-primary collapsed-box">
            <div class="box-header">
                <h3 class="box-title">Quick Edit</h3>

                <div class="box-tools pull-right">
                    <button class="btn btn-default btn-sm"
                            data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                </div>
            </div>
            <div class="box-body" style="display: none;">
                {{ Form::open(['route' => ['admin.jobs.update', $job->id], 'method' => 'PUT']) }}
                @if(!$job->invoiced)
                    <div class="form-group">
                        {{ Form::checkbox('markInvoiced') }}
                        {{ Form::label('markInvoiced', 'Mark as invoiced') }}
                    </div>
                @endif

                <div class="form-group">
                    {{ Form::label('adminComment', 'Comment') }}
                    {{ Form::textarea('adminComment',  $job->admin_comment, ['class' => 'form-control']) }}
                </div>

                {{ Form::submit('Save', ['class' => 'btn btn-default']) }}

                {{ Form::close() }}


            </div>
        </div>

    </div>


@stop